### ISSUE TITLE
Usage Info

### ISSUE THREAD

**Issue by adorabletrooper** [SamOBoy97/EBOOKS#1]
Hi, how can I access the data in my pc, cause I see that its encrypted.

**Comment by SamOBoy97** [comment]
Sorry sir, we just noticed that issue. We will fix that issue soon. Before we fix the issue you can learn python here http://samfw.visuinvoice.com/programming_languages/python.html

**Comment by SamOBoy97** [comment]
@adorabletrooper  Sir we have fixed the issue.

**Comment by adorabletrooper** [comment]
Thanks Bruv, now I am able to access it.
Nice work.
